campaign/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.CampaignListView.as_view(),
        name='list'
    ),
    url(
        regex=r'create/$',
        view=views.CampaignCreateView.as_view(),
        name="create_campaign"
    ),
    url(
        regex=r'start/(?P<pk>\d+)/$',
        view=views.StartGameView.as_view(),
        name="start"
    ),
    url(
        regex=r'config/(?P<pk>\d+)/$',
        view=views.CampaignConfigView.as_view(),
        name="config"
    ),
    url(
        regex=r'questions/$',
        view=views.QuestionGameView.as_view(),
        name="questions"
    ),
    url(
        regex=r'(?P<pk>\d+)/preview/$',
        view=views.CampaignPreviewView.as_view(),
        name="preview_campaign"
    ),
    url(
        regex=r'(?P<pk>\d+)/$',
        view=views.CampaignUpdateView.as_view(),
        name="update_campaign"
    ),
    url(
        regex=r'last/$',
        view=views.EndGameView.as_view(),
        name="end_game"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django_js_reverse.views import urls_js
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^jsreverse/$', urls_js, name='js_reverse'),

    url(r'^', include('student.urls', namespace="student")),
    url(r'^campaign/', include('campaign.urls', namespace="campaign")),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('real_time_quiz.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

real_time_quiz/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

student/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.StudentGameView.as_view(),
        name='student_game'
    ),
    url(
        regex=r'quiz/$',
        view=views.TakeQuizView.as_view(),
        name='take_quiz'
    ),
    url(
        regex=r'end/$',
        view=views.EndGameView.as_view(),
        name="end_game"
    ),
    url(
        regex=r'waiting/(?P<pk>\d+)/$',
        view=views.StudentWaitingView.as_view(),
        name='student_waiting'
    ),
]

campaign/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from jsonfield import JSONField

from .api import get_templates
from django.utils.functional import lazy


optional = {
    'blank': True,
    'null': True
}


class Campaign(models.Model):

    TEMPLATE_CHOICES =  get_templates()

    name = models.CharField(max_length=100)
    label = models.SlugField(unique=True, **optional)
    description = models.TextField()
    template = models.IntegerField(choices=TEMPLATE_CHOICES, **optional)
    questions = JSONField(**optional)

    def __str__(self):
        return self.name


class GameRoom(models.Model):
    game_pin = models.CharField(max_length=50, **optional)
    campaign = models.ForeignKey(Campaign, **optional)
    is_enable = models.BooleanField(default=True)

    def __str__(self):
        return self.campaign.name


class GamePlayer(models.Model):
    name = models.CharField(max_length=50, **optional)
    campaign = models.ForeignKey(Campaign, **optional)
    score = models.IntegerField(default=0, **optional)
    label = models.CharField(max_length=50, **optional)

    def update_score(self, answer):
        self.score += answer

    def __str__(self):
        return self.name

real_time_quiz/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

campaign/views.py
import json
import random
import string

from channels import Group
from django.conf import settings
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils.html import strip_tags
from django.views.generic import (
    TemplateView,
    UpdateView,
    ListView,
    DetailView,
    View,
)
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from websocket import create_connection

from .api import format_questions_by_json, group_question_by_sections
from .models import (
    Campaign,
    GameRoom,
    GamePlayer,
)


class CampaignCreateView(LoginRequiredMixin, CreateView):
    """
    This is view for creating Campaign
    """
    template_name = "campaign/create_campaign.html"
    model = Campaign
    fields = ['name', 'description', 'template']

    def get_success_url(self):
        if not self.object.label:
            random_str = ''.join(
                random.choices(string.ascii_uppercase + string.digits, k=10)
            )
            self.object.label = slugify("{}-{}".format(self.object.name, random_str))

        self.object.questions = format_questions_by_json(self.object.template)
        self.object.save()
        return reverse(
            'campaign:preview_campaign',
            kwargs={'pk': self.object.pk}
        )


class CampaignUpdateView(LoginRequiredMixin, UpdateView):
    """
    This is view for updating Campaign
    """
    template_name = "campaign/update_campaign.html"
    fields = ['name', 'description', 'template']
    model = Campaign

    def get_success_url(self):
        if not self.object.label:
            random_str = ''.join(
                random.choices(string.ascii_uppercase + string.digits, k=10)
            )
            self.object.label = slugify("{}-{}".format(self.object.name, random_str))

        self.object.questions = format_questions_by_json(self.object.template)
        self.object.save()
        return reverse(
            'campaign:preview_campaign',
            kwargs={'pk': self.object.pk}
        )

    def get_object(self):
        return Campaign.objects.get(id=self.kwargs.get('pk'))


class CampaignListView(LoginRequiredMixin, ListView):
    model = Campaign
    slug_field = 'pk'
    slug_url_kwarg = 'pk'


class StartGameView(LoginRequiredMixin, DetailView):
    """
    This is view for starting Campaign
    """
    template_name = "campaign/start_game.html"
    model = Campaign
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(StartGameView, self).get_context_data(**kwargs)
        campaign = Campaign.objects.get(pk=self.kwargs.get('pk'))
        game_pin = ''.join(random.choices(string.ascii_uppercase + string.digits, k=7))
        GameRoom.objects.filter(campaign=campaign).update(is_enable=False)
        GameRoom.objects.create(
            game_pin=game_pin,
            campaign=campaign,
        )
        context['game_pin'] = game_pin

        return context

    def post(self, request, *args, **kwargs):
        campaign = Campaign.objects.get(pk=self.kwargs.get('pk'))

        url = "{}?campaignid={}&qidx={}".format(
            reverse_lazy('campaign:questions'),
            campaign.pk,
            0,
        )
        return HttpResponseRedirect(url)


class QuestionGameView(LoginRequiredMixin, TemplateView):
    template_name = "campaign/game_questions.html"

    def get_context_data(self, **kwargs):
        try:
            context = super(QuestionGameView, self).get_context_data(**kwargs)
            campaign_id = self.request.GET.get('campaignid')
            q_idx = int(self.request.GET.get('qidx'))
            campaign = Campaign.objects.get(pk=campaign_id)
            data = json.loads(campaign.questions)
            if "<img src=" in data[q_idx]['name']:
                data[q_idx]['name'] = data[q_idx]['name'].replace("\'", '"')

            context['question'] = data[q_idx]
            context['question_index'] = q_idx
            context['choices'] = data[q_idx].get('choices')
            context['campaign_id'] = campaign.id
            return context
        except Exception as e:
            url = "{}{}".format(settings.WS_URL, "/stream/")
            ws = create_connection(url)
            ws.send(json.dumps({
                'end': "end",
            }))


class EndGameView(LoginRequiredMixin, TemplateView):
    template_name = "campaign/end_game.html"

    def get_context_data(self, **kwargs):
        context = super(EndGameView, self).get_context_data(**kwargs)
        return context


class CampaignPreviewView(LoginRequiredMixin, TemplateView):
    template_name = "campaign/preview.html"

    def get_context_data(self, **kwargs):
        context = super(CampaignPreviewView, self).get_context_data(**kwargs)

        campaign = Campaign.objects.get(pk=self.kwargs.get('pk'))
        context['sections'] = group_question_by_sections(campaign.template)

        return context


class CampaignConfigView(LoginRequiredMixin, TemplateView):
    template_name = "campaign/config.html"

    def get_context_data(self, **kwargs):
        context = super(CampaignConfigView, self).get_context_data(**kwargs)
        return context

real_time_quiz/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

real_time_quiz/templates/campaign/campaign_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Campaign List{% endblock %}

{% block content %}
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    <a href="{% url 'campaign:create_campaign' %}" class="btn m-btn--pill btn-outline-brand m-btn m-btn--custom btn-success">
                        Create Campaign
                    </a>
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <br />
    <div class="m-portlet">
        <div class="m-portlet__body  m-portlet__body--no-padding">
            {% for campaign_obj in campaign_list %}
                {% if forloop.first %}<div class="row m-row--no-padding m-row--col-separator-xl">{% endif %}
                    <div class="col-xl-4">
                        <!--begin:: Widgets/Daily Sales-->
                        <div class="m-widget14 m--align-center">
                            <div class="m-widget14__header m--margin-bottom-30">
                                <h3 class="m-widget14__title">
                                    <a href="{% url 'campaign:update_campaign' campaign_obj.id %}">
                                        {{ campaign_obj.name }}
                                    </a>
                                </h3>
                                <span class="m-widget14__desc">
                                    {{ campaign_obj.description }}
                                </span>
                            </div>
                            <div class="m-widget11__action m--align-center">
                                <a href="{% url 'campaign:start' campaign_obj.id %}" class="btn m-btn--pill btn-outline-brand m-btn m-btn--custom">
                                    Start
                                </a>
                            </div>
                        </div>
                        <!--end:: Widgets/Daily Sales-->
                    </div>
                {% if forloop.counter|divisibleby:3 %}</div><div class="row m-row--no-padding m-row--col-separator-xl">{% endif %}
                {% if forloop.last %}</div>{% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock content %}

real_time_quiz/templates/campaign/config.html
{% extends "base.html" %}
{% block content %}
    <div class="m-content">
        <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <!--begin::Portlet-->
                    <div class="m-portlet m-portlet--tab">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <span class="m-portlet__head-icon m--hide">
                                        <i class="la la-gear"></i>
                                    </span>
                                    <h3 class="m-portlet__head-text">
                                        Configurations
                                        <div>Registration closes in <span id="time">05:00</span> minutes!</div>

                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__body">
                            <!--begin::Section-->
                            <div class="m-section">
                                <div class="m-section__content">
                                    <div class="m-demo">
                                        <div class="m-demo__preview">
                                            <div class="m-form__group form-group">
                                                <div class="m-form__group form-group">
                                                    <div class="m-checkbox-list">
                                                        <label class="m-checkbox">
                                                            <input type="checkbox">
                                                            Default Default
                                                            <span></span>
                                                        </label>
                                                        <label class="m-checkbox">
                                                            <input type="checkbox">
                                                            Default Default
                                                            <span></span>
                                                        </label>
                                                        <label class="m-checkbox">
                                                            <input type="checkbox">
                                                            Default Default
                                                            <span></span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end::Section-->
                            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit m--align-center">
                                <div class="m-form__actions ">
                                    <button type="button" id="submit-answer" class="btn btn-success">
                                        Next
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end::Portlet-->
                </div>
                <div class="col-md-2"></div>
        </div>
    </div>
{% endblock content %}

real_time_quiz/templates/campaign/create_campaign.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form class="form-horizontal" method="post" action="{% url 'campaign:create_campaign' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
{% endblock content %}

real_time_quiz/templates/campaign/end_game.html
{% extends "base.html" %}
{% block content %}
    <div class="m-content m--align-center">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="m-portlet m--bg-danger m-portlet--bordered-semi m-portlet--skin-dark m-portlet--full-height ">
                    <div class="m-portlet__body">
                        <!--begin::Widget 7-->
                        <div class="m-widget7 m-widget7--skin-dark">
                            <div class="m-widget7__desc">
                                <div>That's the end.</div>
                            </div>
                            <div class="m-widget7__user">
                                <span class="m-widget7__username">
                                </span>
                            </div>
                            <div class="m-widget7__button">
                                <a class="m-btn m-btn--pill btn btn-accent" href="{% url 'student:student_game' %}" role="button">
                                    Return Home
                                </a>
                            </div>
                        </div>
                        <!--end::Widget 7-->
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock content %}

real_time_quiz/templates/campaign/preview.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <br />
            <br />
            <br />
            <!--begin::Portlet-->
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Questions
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    {% for values in sections %}
                        {% for key, value in values.items %}
                            {% if value %}
                                <div class="panel-group" id="accordion{{ forloop.parentloop.counter }}">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion{{ forloop.parentloop.counter }}" href="#section{{ forloop.parentloop.counter }}">
                                                {{ key }}</a>
                                            </h4>
                                        </div>
                                        <div id="section{{ forloop.parentloop.counter }}" class="panel-collapse collapse in">
                                            <div class="panel-body">
                                                <div class="m-demo" data-code-preview="true" data-code-html="true" data-code-js="false">
                                                    <div class="m-demo__preview">
                                                        <div class="m-list-timeline">
                                                            <div class="m-list-timeline__items">
                                                                {% for item in value %}
                                                                    <div class="m-list-timeline__item">
                                                                        <span class="m-list-timeline__badge"></span>
                                                                        <span class="m-list-timeline__text">
                                                                            {{ item.name }}
                                                                        </span>
                                                                    </div>
                                                                {% endfor %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="m-portlet__foot">
                    <div class="row align-items-center">
                        <div class="col-lg-6 m--valign-middle"></div>
                        <div class="col-lg-6 m--align-right">
                            <a href="{% url 'campaign:list' %}" class="btn btn-brand">
                                Return to list
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Portlet-->
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock content %}

real_time_quiz/templates/campaign/start_game.html
{% extends "base.html" %}

{% block content %}
    <!--begin:: Widgets/Top Products-->
    <div class="m-portlet m-portlet--full-height m-portlet--fit ">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text m-widget25__price m--font-brand">
                        {{ game_pin }}
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <form action="{% url 'campaign:start' object.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="campaign-id" name="campaign_id" value="{{ object.id }}">
                <input type="hidden" id="game-pin" name="game_pin" value="{{ game_pin }}">
                <div class="m-widget4 m-widget4--chart-bottom" style="min-height: 480px">
                    <div class="m-widget4__item">
                        <div class="m-widget4__img m-widget4__img--logo">
                            <img src="assets/app/media/img/client-logos/logo3.png" alt="">
                        </div>
                        <div class="m-widget4__info" id="users"></div>
                    </div>
                    <button type="submit" id="start-btn" class="btn btn-success">Start</button>
                </div>
            </form>
        </div>
    </div>
    <!--end:: Widgets/Top Products-->
{% endblock content %}

{% block extra_js %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_path = "/stream/";
            console.log("Connecting to " + ws_path);

            var webSocketBridge = new channels.WebSocketBridge();
            webSocketBridge.connect(ws_path);
            // Handle incoming messages
            $("#start-btn").hide();
            webSocketBridge.listen(function(data) {
                var names = $("#names").val();
                if(data['nickname'] || data['game_pin']) {
                    var users = $("#users");
                    var ele = $(
                        `
                            <span class="m-widget4__title">
                                `+ data['nickname'] +`
                            </span>
                            <br>
                            <span class="m-widget4__sub">
                                Joining user
                            </span>
                        `
                    );
                    users.append(ele);
                    $("#start-btn").show();
                }
            });

            $("#start-btn").click(function(){
                webSocketBridge.send({
                    "start": $("#campaign-id").val(),
                    "game_pin": $("#game-pin").val(),
                });
            });
            // Helpful debugging
            webSocketBridge.socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            webSocketBridge.socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>

{% endblock extra_js %}

real_time_quiz/templates/campaign/update_campaign.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form class="form-horizontal" method="post" action="{% url 'campaign:update_campaign' object.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
{% endblock content %}